sudo: require
language: generic

services:
  - docker

before_install:
  - docker build  -t toplaa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true toplaa/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-340729127361"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY